### PR TITLE
Mac Wallet

### PR DESCRIPTION
**Pull request by meyer9**
# Work in progress - do not merge

I've tested this on my computer with OSX 10.12 and 10.13. It would be nice to have some more tests just to make sure it works. Please comment below if it works or doesn't work on your Mac machine, including the mac version and specs.

I've also uploaded a binary in case someone doesn't want to compile it.

### CODE REVIEW

**Comment by meyer9** [comment]
Here is the binary for Mac:
[Phore-Qt.app.zip](https://github.com/phoreproject/Phore/files/1464025/Phore-Qt.app.zip)

**Comment by yvbeek** [comment]
@meyer9 Thanks! It would be great to have this version released for Mac users.

I noticed no releases on the Releases page, is this the main repository of the project?

**Comment by meyer9** [comment]
Yes it is, we're working to make this Github repo more used (adding Gitian support, etc.), but it's still a work in progress. I'm compiling a new version now.

**Comment by Zyphrax** [comment]
@meyer9 Thank you! Looking forward to the new Mac version.

**Comment by yvbeek** [comment]
@meyer9 Could you please build a new Mac version? Thanks!

**Pull request merged**
